name:                proto-voice-model
version:             0.1.0.0
github:              "ANONYMIZED"
license:             BSD3
author:              "ANONYMOUS"
maintainer:          "ANONYMOUS"
copyright:           "ANONYMOUS"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A model of proto-voices

dependencies:
- base >= 4.7 && < 5
- musicology-pitch
- musicology-core
- musicology-musicxml
- text
- containers
- unordered-containers
- multiset
- transformers
- mtl
- indexed
- do-notation
- microlens
- hashable
- algebraic-graphs
- semirings
- parallel
- deepseq
- data-default
- diagrams-lib
- diagrams-svg
- colour
- process

library:
  source-dirs: src

executables:
  ismir2021:
    main: app/MainISMIR.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-voice-model

tests:
  proto-voice-model-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-voice-model
