name:                proto-voice-model
version:             0.1.0.0
github:              "chfin/proto-voice-model"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "Christoph Finkensiep"

extra-source-files:
- README.md
- ChangeLog.md

extra-doc-files:
  - doc-images/*.svg

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chfin/proto-voice-model#readme>

dependencies:
- base >= 4.7 && < 5
- musicology-pitch
- musicology-core
- musicology-musicxml
- text
- containers
- unordered-containers
- vector
- vector-sized
- strict-list
- strict
- extra
- transformers
- mtl
- stm
- fin
- typenums
- conjugate-programs
- random
- mwc-random
- mwc-probability
- random-shuffle
- primitive
- indexed
- do-notation
- microlens
- microlens-th
- hashable
- semirings
- foldl
- aeson
- parallel
- deepseq
- nothunks
- process
- filepath
- filepattern
- pretty-simple
- statistics
- log-domain
- matplotlib
- hasktorch
- libtorch-ffi
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- Chart
- Chart-gtk
- Chart-cairo
- palette
- terminal-progress-bar

language: GHC2021

library:
  source-dirs: src
  # when:
  #   condition: false
  #   exposed-modules:
  #     - RL.A2CHelpers
  #     - RL.A2C
  #     - RL.DQN
  #     - RL.Train
  #     - RL
  ghc-options: []
    # - -fplugin GHC.TypeLits.KnownNat.Solver
    # - -fplugin GHC.TypeLits.Normalise
  #- -Wall

executables:
  # parse:
  #   main:                app/MainParsing.hs
  #   #source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - proto-voice-model

  learn:
    main:                app/MainLearning.hs
    #source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-voice-model
    
  # examples:
  #   main:                app/MainExamples.hs
  #   #source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - proto-voice-model

  # ismir2021:
  #   main: app/MainISMIR.hs
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - proto-voice-model

  rl-chords:
    main: app/MainRLChords.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-voice-model

  torch-test:
    main: app/MainTorchTest.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - pipes
      - safe-exceptions

tests:
  proto-voice-model-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-voice-model
